### ISSUE TITLE
Add video controls keybinds

### ISSUE THREAD

**Issue by lexesjan** [lexesjan/typescript-aniskip-extension#113]
Add keybinds for moving the current time forwards and backwards by one frame like on YouTube. The default keybinds are `,` and `.`. We can also add keybinds to manually skip an opening / ending (+-90s to the current time).

**Comment by MulverineX** [comment]
That second part is already in MALSync, default bind is ctrl+left/right

**Comment by lexesjan** [comment]
> That second part is already in MALSync, default bind is ctrl+left/right

That is true, this may still be beneficial for people who do not also have MALSync installed (as it was suggested before).
