### ISSUE TITLE
Manual skip/seek is not working correctly

### ISSUE THREAD

**Issue by thijsi123** [lexesjan/typescript-aniskip-extension#370]
### Describe the bug

The seek forward key always adds the wrong amount of seconds, no matter what my skip time is set to.

### To Reproduce

1. change skip time(or leave it be)
2. set shortcut key on seek option.
3. use the seek option.
5. See error(wrong time skip)

### Device Information

1. Extension version: 1.8.7
2. Browser:
   1. Type: Edge 
   2. Version: 101.0.1210.47 (Official build) (64-bit)
   3. Type: Chrome
   4. Version: 101.0.4951.67 (Official Build) (64-bit)
5. Operating system:
   1. Type: Windows
   2. Version: 21H2 
   3. OS BUILD: 19044.1706

### Screenshots

![image](https://user-images.githubusercontent.com/64159148/168508928-c351b016-a4d8-4a56-bb4e-9c79fd6b148e.png) 
Animixplay^

![image](https://user-images.githubusercontent.com/64159148/168509107-f571296f-b2cc-4238-9fa9-6290603e283d.png)
9anime^
Both used only one skip whith the skip time set to 100 seconds.
![image](https://user-images.githubusercontent.com/64159148/168508905-7792b337-4ee6-401a-b372-e5ec42bff607.png)

### Code of Conduct

- [X] I agree to fill in the correct information

**Comment by thijsi123** [comment]
Seems like it is the same as #366 should I close this one?

**Comment by lexesjan** [comment]
Thanks for submitting the bug. I can't seem to reproduce it however. When you rebind the keybinds, what do you rebind it to? I suspect that it is probably conflicting with the player keybinds and adding extra time e.g. if you set it to right arrow key it would add 90s (default) + 5s (player specific keybind).

**Comment by thijsi123** [comment]
I tried shift-right_arrow_key and ctrl-right_arrow_key, I'll try something else.

**Comment by thijsi123** [comment]
I'm sorry but it seems that those 2 combinations are the culprit.
I tried using ctrl only and it worked perfectly. Thank you ^^

**Comment by lexesjan** [comment]
No worries, thanks for bringing this up. I'll try and have a look to see if any overlapping keybinds can be disabled so that the expected behaviour will occur.
