### ISSUE TITLE
Is possible use it in youtube for playlist?

### ISSUE THREAD

**Issue by Milor123** [lexesjan/typescript-aniskip-extension#508]
### Is your feature request related to a problem?

I would like use it in a playlist or import a bulk URLs with the times to be skipped. 
Thank you very much!!!

### Describe the solution you'd like

NP

### Code of Conduct

- [X] I agree to fill in the correct information

**Comment by lexesjan** [comment]
The extension was not designed with youtube in mind. You are probably looking for the [Sponsorblock Extension](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone?hl=en) which does what you might be looking for.
